const timestampFields = ['created_at', 'updated_at'];

module.exports = {
  roles: {
    pk: 'id',
    fields: ['name', 'description', 'permissions', ...timestampFields],
    jsonFields: ['permissions'],
  },
  countries: {
    pk: 'id',
    fields: ['code', 'name', 'region', 'coordinator_id', 'status', ...timestampFields],
    enums: {
      status: ['active', 'inactive'],
    },
  },
  users: {
    pk: 'id',
    fields: [
      'google_id',
      'email',
      'first_name',
      'last_name',
      'phone',
      'profile_image_url',
      'password_hash',
      'role_id',
      'country_id',
      'status',
      'last_login_at',
      ...timestampFields,
    ],
    enums: {
      status: ['active', 'inactive', 'suspended'],
    },
    aliases: {
      googleId: 'google_id',
      firstName: 'first_name',
      lastName: 'last_name',
      profileImageUrl: 'profile_image_url',
      roleId: 'role_id',
      countryId: 'country_id',
      lastLoginAt: 'last_login_at',
    },
  },
  programs: {
    pk: 'id',
    fields: [
      'name',
      'description',
      'category',
      'coordinator_id',
      'status',
      'max_volunteers',
      'specialization_required',
      ...timestampFields,
    ],
    enums: {
      status: ['active', 'inactive', 'archived'],
    },
    aliases: {
      coordinatorId: 'coordinator_id',
      maxVolunteers: 'max_volunteers',
      specializationRequired: 'specialization_required',
    },
  },
  volunteers: {
    pk: 'id',
    fields: [
      'user_id',
      'specialization',
      'education_level',
      'experience_years',
      'availability',
      'emergency_contact_name',
      'emergency_contact_phone',
      'preferences',
      'status',
      'total_hours',
      'total_sessions',
      ...timestampFields,
    ],
    jsonFields: ['preferences'],
    enums: {
      status: ['active', 'inactive', 'pending', 'suspended'],
    },
    aliases: {
      userId: 'user_id',
      educationLevel: 'education_level',
      experienceYears: 'experience_years',
      emergencyContactName: 'emergency_contact_name',
      emergencyContactPhone: 'emergency_contact_phone',
      totalHours: 'total_hours',
      totalSessions: 'total_sessions',
    },
  },
  volunteer_programs: {
    pk: 'id',
    fields: [
      'volunteer_id',
      'program_id',
      'start_date',
      'end_date',
      'status',
      'progress_percentage',
      'certification_date',
      ...timestampFields,
    ],
    enums: {
      status: ['enrolled', 'active', 'completed', 'dropped'],
    },
    aliases: {
      volunteerId: 'volunteer_id',
      programId: 'program_id',
      startDate: 'start_date',
      endDate: 'end_date',
      progressPercentage: 'progress_percentage',
      certificationDate: 'certification_date',
    },
  },
  program_groups: {
    pk: 'id',
    fields: [
      'program_id',
      'name',
      'description',
      'coordinator_id',
      'coach_id',
      'start_date',
      'end_date',
      'max_capacity',
      'status',
      ...timestampFields,
    ],
    enums: {
      status: ['active', 'inactive', 'completed', 'cancelled'],
    },
    aliases: {
      programId: 'program_id',
      coordinatorId: 'coordinator_id',
      coachId: 'coach_id',
      startDate: 'start_date',
      endDate: 'end_date',
      maxCapacity: 'max_capacity',
    },
  },
  volunteer_group_members: {
    pk: 'id',
    fields: [
      'group_id',
      'volunteer_id',
      'role_in_group',
      'status',
      'joined_at',
      'left_at',
      'notes',
      ...timestampFields,
    ],
    enums: {
      role_in_group: ['member', 'lead'],
      status: ['active', 'inactive', 'completed', 'dropped'],
    },
    aliases: {
      groupId: 'group_id',
      volunteerId: 'volunteer_id',
      roleInGroup: 'role_in_group',
      joinedAt: 'joined_at',
      leftAt: 'left_at',
    },
  },
  volunteer_documents: {
    pk: 'id',
    fields: [
      'volunteer_id',
      'document_type',
      'original_file_name',
      'stored_file_name',
      'file_path',
      'file_url',
      'mime_type',
      'file_size',
      'status',
      'rejection_note',
      'reviewed_by',
      'reviewed_at',
      'uploaded_at',
      ...timestampFields,
    ],
    enums: {
      status: ['pending', 'approved', 'rejected'],
    },
    aliases: {
      volunteerId: 'volunteer_id',
      documentType: 'document_type',
      originalFileName: 'original_file_name',
      storedFileName: 'stored_file_name',
      filePath: 'file_path',
      fileUrl: 'file_url',
      mimeType: 'mime_type',
      fileSize: 'file_size',
      rejectionNote: 'rejection_note',
      reviewedBy: 'reviewed_by',
      reviewedAt: 'reviewed_at',
      uploadedAt: 'uploaded_at',
    },
  },
  volunteer_form_requests: {
    pk: 'id',
    fields: [
      'volunteer_id',
      'program_id',
      'requested_by',
      'action_type',
      'form_type',
      'status',
      'due_date',
      'form_data',
      'submitted_at',
      'reviewed_by',
      'reviewed_at',
      'review_notes',
      ...timestampFields,
    ],
    jsonFields: ['form_data'],
    enums: {
      action_type: ['onboarding', 'graduation'],
      form_type: ['adult', 'minor'],
      status: ['requested', 'in_progress', 'submitted', 'approved', 'rejected', 'expired'],
    },
    aliases: {
      volunteerId: 'volunteer_id',
      programId: 'program_id',
      requestedBy: 'requested_by',
      actionType: 'action_type',
      formType: 'form_type',
      dueDate: 'due_date',
      formData: 'form_data',
      submittedAt: 'submitted_at',
      reviewedBy: 'reviewed_by',
      reviewedAt: 'reviewed_at',
      reviewNotes: 'review_notes',
    },
  },
  sessions: {
    pk: 'id',
    fields: [
      'program_id',
      'coordinator_id',
      'coach_id',
      'title',
      'description',
      'session_type',
      'delivery_mode',
      'scheduled_date',
      'start_time',
      'end_time',
      'location',
      'virtual_link',
      'max_capacity',
      'current_attendance',
      'registration_link',
      'qr_code',
      'status',
      'recording_url',
      'materials_url',
      ...timestampFields,
    ],
    enums: {
      session_type: ['general', 'specialized', 'follow-up'],
      delivery_mode: ['virtual', 'in-person', 'hybrid'],
      status: ['scheduled', 'in-progress', 'completed', 'cancelled'],
    },
    aliases: {
      programId: 'program_id',
      coordinatorId: 'coordinator_id',
      coachId: 'coach_id',
      sessionType: 'session_type',
      deliveryMode: 'delivery_mode',
      scheduledDate: 'scheduled_date',
      startTime: 'start_time',
      endTime: 'end_time',
      virtualLink: 'virtual_link',
      maxCapacity: 'max_capacity',
      currentAttendance: 'current_attendance',
      registrationLink: 'registration_link',
      qrCode: 'qr_code',
      recordingUrl: 'recording_url',
      materialsUrl: 'materials_url',
    },
  },
  session_attendance: {
    pk: 'id',
    fields: [
      'session_id',
      'volunteer_id',
      'attendance_method',
      'status',
      'registered_at',
      'attended_at',
      'check_in_time',
      'check_out_time',
      'notes',
      ...timestampFields,
    ],
    enums: {
      attendance_method: ['link', 'qr', 'manual'],
      status: ['present', 'absent', 'excused'],
    },
    aliases: {
      sessionId: 'session_id',
      volunteerId: 'volunteer_id',
      attendanceMethod: 'attendance_method',
      registeredAt: 'registered_at',
      attendedAt: 'attended_at',
      checkInTime: 'check_in_time',
      checkOutTime: 'check_out_time',
    },
  },
  whatsapp_reminders: {
    pk: 'id',
    fields: [
      'reminder_type',
      'volunteer_id',
      'session_id',
      'phone',
      'message',
      'status',
      'twilio_message_sid',
      'error_message',
      'sent_at',
      ...timestampFields,
    ],
    enums: {
      reminder_type: ['future', 'absence'],
      status: ['sent', 'failed', 'dry-run'],
    },
    aliases: {
      reminderType: 'reminder_type',
      volunteerId: 'volunteer_id',
      sessionId: 'session_id',
      twilioMessageSid: 'twilio_message_sid',
      errorMessage: 'error_message',
      sentAt: 'sent_at',
    },
  },
  follow_ups: {
    pk: 'id',
    fields: [
      'volunteer_id',
      'coordinator_id',
      'follow_up_type',
      'status',
      'scheduled_date',
      'completed_date',
      'contact_method',
      'notes',
      'outcome',
      ...timestampFields,
    ],
    enums: {
      follow_up_type: ['check-in', 'motivation', 're-engagement', 'support'],
      status: ['pending', 'in-progress', 'completed', 'cancelled'],
      contact_method: ['email', 'whatsapp', 'call', 'in-person'],
    },
    aliases: {
      volunteerId: 'volunteer_id',
      coordinatorId: 'coordinator_id',
      followUpType: 'follow_up_type',
      scheduledDate: 'scheduled_date',
      completedDate: 'completed_date',
      contactMethod: 'contact_method',
    },
  },
  email_templates: {
    pk: 'id',
    fields: ['name', 'subject', 'body', 'description', 'variables', 'template_type', 'is_active', ...timestampFields],
    jsonFields: ['variables'],
    booleanFields: ['is_active'],
    enums: {
      template_type: ['welcome', 'reminder', 'follow-up', 'report', 'custom'],
    },
    aliases: {
      templateType: 'template_type',
      isActive: 'is_active',
    },
  },
  settings: {
    pk: 'id',
    fields: ['country_id', 'setting_key', 'setting_value', 'setting_type', 'description', ...timestampFields],
    enums: {
      setting_type: ['string', 'number', 'boolean', 'json'],
    },
    aliases: {
      countryId: 'country_id',
      settingKey: 'setting_key',
      settingValue: 'setting_value',
      settingType: 'setting_type',
    },
  },
  audit_log: {
    pk: 'id',
    fields: ['user_id', 'action', 'entity_type', 'entity_id', 'changes_data', 'ip_address', 'user_agent', 'created_at'],
    jsonFields: ['changes_data'],
    aliases: {
      userId: 'user_id',
      entityType: 'entity_type',
      entityId: 'entity_id',
      changesData: 'changes_data',
      ipAddress: 'ip_address',
      userAgent: 'user_agent',
    },
  },
};
